export const data = [
    {id: 1,
    img:'image 12.png', 
    rating:'5.0', 
    reviews:'6', 
    location:'USA', 
    title:'Life lessons with Katie Zaferes',
    price:'$136',
    openspots: 0},
    {id: 2,
    img:'wedding-photography 1.png', 
    rating:'5.0', 
    reviews:'30', 
    location:'USA', 
    title:'Learn wedding photography',
    price:'$125',
    openspots: 2},
    {
    id: 3,
    img:'mountain-bike 1.png', 
    rating:'4.8', 
    reviews:'2', 
    location:'Online', 
    title:'Group Mountain Biking',
    price:'$50',
    openspots: 1
    },
    {id: 4,
    img:'image 12.png', 
    rating:'5.0', 
    reviews:'6', 
    location:'USA', 
    title:'Life lessons with Katie Zaferes',
    price:'$136',
    openspots: 8},
    {id: 5,
    img:'wedding-photography 1.png', 
    rating:'5.0', 
    reviews:'30', 
    location:'USA', 
    title:'Learn wedding photography',
    price:'$125',
    openspots: 8},
    {
    id: 6,
    img:'mountain-bike 1.png', 
    rating:'4.8', 
    reviews:'2', 
    location:'USA', 
    title:'Group Mountain Biking',
    price:'$50',
    openspots: 8
    }]

export default {data}